using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace AtendTeleMedicina.Domain.Enums
{
    public enum Etnia
    {
        //Regras: Campo Condicional - Só deve ser preenchido se o campo racaCorCidadao = 5. Neste caso o preenchimento é obrigatório.
        [Display(Name = "ACONA (WAKONAS, NACONAS, JAKONA, ACORANES)")]
        ACONA = 1,
        [Display(Name = "AIKANA (AIKANA, MAS SAKA, TUBARAO)")]
        AIKANA = 2,
        [Display(Name = "AJURU")]
        AJURU = 3,
        [Display(Name = "AKUNSU (AKUNT''SU)")]
        AKUNSU = 4,
        [Display(Name = "AMANAYE")]
        AMANAYE = 5,
        [Display(Name = "AMONDAWA")]
        AMONDAWA = 6,
        [Display(Name = "ANAMBE")]
        ANAMBE = 7,
        [Display(Name = "APARAI (APALAI)")]
        APARAI = 8,
        [Display(Name = "APIAKA (APIACA)")]
        APIAKA = 9,
        [Display(Name = "APINAYE (APINAJE/APINAIE/APINAGE)")]
        APINAYE = 10,
        [Display(Name = "APURINA (APORINA, IPURINA, IPURINA, IPURINAN)")]
        APURINA = 11,
        [Display(Name = "ARANA (ARACUAI DO VALE DO JEQUITINHONHA)")]
        ARANA = 12,
        [Display(Name = "ARAPASO (ARAPACO)")]
        ARAPASO = 13,
        [Display(Name = "ARARA DE RONDONIA (KARO, URUCU, URUKU)")]
        ARARADERONDONIA = 14,
        [Display(Name = "ARARA DO ACRE (SHAWANAUA, AMAWAKA)")]
        ARARADOACRE = 15,
        [Display(Name = "ARARA DO ARIPUANA (ARARA DO BEIRADAO/ARI-PUANA)")]
        ARARADOARIPUANA = 16,
        [Display(Name = "ARARA DO PARA (UKARAGMA, UKARAMMA)")]
        ARARADOPARA = 17,
        [Display(Name = "ARAWETE (ARAUETE)")]
        ARAWETE = 18,
        [Display(Name = "ARIKAPU (ARICAPU, ARIKAPO, MASUBI, MAXUBI)")]
        ARIKAPU = 19,
        [Display(Name = "ARIKEM (ARIQUEN, ARIQUEME, ARIKEME)")]
        ARIKEM = 20,
        [Display(Name = "ARIKOSE (ARICOBE)")]
        ARIKOSE = 21,
        [Display(Name = "ARUA")]
        ARUA = 22,
        [Display(Name = "ARUAK (ARAWAK)")]
        ARUAK = 23,
        [Display(Name = "ASHANINKA (KAMPA)")]
        ASHANINKA = 24,
        [Display(Name = "ASURINI DO TOCANTINS (AKUAWA/AKWAWA)")]
        ASURINIDOTOCANTINS = 25,
        [Display(Name = "ASURINI DO XINGU (AWAETE)")]
        ASURINIDOXINGU = 26,
        [Display(Name = "ATIKUM (ATICUM)")]
        ATIKUM = 27,
        [Display(Name = "AVA - CANOEIRO")]
        AVA = 28,
        [Display(Name = "AWETI (AUETI/AUETO)")]
        AWETI = 29,
        [Display(Name = "BAKAIRI (KURA, BACAIRI)")]
        BAKAIRI = 30,
        [Display(Name = "BANAWA YAFI (BANAWA, BANAWA-JAFI)")]
        BANAWAYAFI = 31,
        [Display(Name = "BANIWA (BANIUA, BANIVA, WALIMANAI, WAKUENAI)")]
        BANIWA = 32,
        [Display(Name = "BARA (WAIPINOMAKA)")]
        BARA = 33,
        [Display(Name = "BARASANA (HANERA)")]
        BARASANA = 34,
        [Display(Name = "BARE")]
        BARE = 35,
        [Display(Name = "BORORO (BOE)")]
        BORORO = 36,
        [Display(Name = "BOTOCUDO (GEREN)")]
        BOTOCUDO = 37,
        [Display(Name = "CANOE")]
        CANOE = 38,
        [Display(Name = "CASSUPA")]
        CASSUPA = 39,
        [Display(Name = "CHAMACOCO")]
        CHAMACOCO = 40,
        [Display(Name = "CHIQUITANO (XIQUITANO)")]
        CHIQUITANO = 41,
        [Display(Name = "CIKIYANA (SIKIANA)")]
        CIKIYANA = 42,
        [Display(Name = "CINTA LARGA (MATETAMAE)")]
        CINTALARGA = 43,
        [Display(Name = "COLUMBIARA (CORUMBIARA)")]
        COLUMBIARA = 44,
        [Display(Name = "DENI")]
        DENI = 45,
        [Display(Name = "DESANA (DESANA, DESANO, DESSANO, WIRA, UMUKOMASA)")]
        DESANA = 46,
        [Display(Name = "DIAHUI (JAHOI, JAHUI, DIARROI)")]
        DIAHUI = 47,
        [Display(Name = "ENAWENE-NAWE (SALUMA)")]
        ENAWENENAWE = 48,
        [Display(Name = "FULNI-O")]
        FULNIO = 49,
        [Display(Name = "GALIBI (GALIBI DO OIAPOQUE, KARINHA)")]
        GALIBI = 50,
        [Display(Name = "GALIBI MARWORNO (GALIBI DO UACA, ARUA)")]
        GALIBIMARWORNO = 51,
        [Display(Name = "GAVIAO DE RONDONIA (DIGUT)")]
        GAVIAODERONDONIA = 52,
        [Display(Name = "GAVIAO KRIKATEJE")]
        GAVIAOKRIKATEJE = 53,
        [Display(Name = "GAVIAO PARKATEJE (PARKATEJE)")]
        GAVIAOPARKATEJE = 54,
        [Display(Name = "GAVIAO PUKOBIE (PUKOBIE, PYKOPJE, GAVIAO DO MARANHAO)")]
        GAVIAOPUKOBIE = 55,
        [Display(Name = "GUAJA (AWA, AVA)")]
        GUAJA = 56,
        [Display(Name = "GUAJAJARA (TENETEHARA)")]
        GUAJAJARA = 57,
        [Display(Name = "GUARANI KAIOWA (PAI TAVYTERA)")]
        GUARANIKAIOWA = 58,
        [Display(Name = "GUARANI M''BYA")]
        GUARANIMBYA = 59,
        [Display(Name = "GUARANI NANDEVA (AVAKATUETE, CHIRIPA, NHANDEWA, AVA GUARANI)")]
        GUARANINANDEVA = 60,
        [Display(Name = "GUATO")]
        GUATO = 61,
        [Display(Name = "HIMARIMA (HIMERIMA)")]
        HIMARIMA = 62,
        [Display(Name = "INGARIKO (INGARICO, AKAWAIO, KAPON)")]
        INGARIKO = 63,
        [Display(Name = "IRANXE (IRANTXE)")]
        IRANXE = 64,
        [Display(Name = "ISSE")]
        ISSE = 65,
        [Display(Name = "JABOTI (JABUTI, KIPIU, YABYTI)")]
        JABOTI = 66,
        [Display(Name = "JAMAMADI (YAMAMADI, DJEOROMITXI)")]
        JAMAMADI = 67,
        [Display(Name = "JARAWARA")]
        JARAWARA = 68,
        [Display(Name = "JIRIPANCO (JERIPANCO, GERIPANCO)")]
        JIRIPANCO = 69,
        [Display(Name = "JUMA (YUMA)")]
        JUMA = 70,
        [Display(Name = "JURUNA")]
        JURUNA = 71,
        [Display(Name = "JURUTI (YURITI)")]
        JURUTI = 72,
        [Display(Name = "KAAPOR (URUBU-KAAPOR, KA''APOR, KAAPORTE)")]
        KAAPOR = 73,
        [Display(Name = "KADIWEU (CADUVEO, CADIUEU)")]
        KADIWEU = 74,
        [Display(Name = "KAIABI (CAIABI, KAYABI)")]
        KAIABI = 75,
        [Display(Name = "KAIMBE (CAIMBE)")]
        KAIMBE = 76,
        [Display(Name = "KAINGANG (CAINGANGUE)")]
        KAINGANG = 77,
        [Display(Name = "KAIXANA (CAIXANA)")]
        KAIXANA = 78,
        [Display(Name = "KALABASSA (CALABASSA, CALABACAS)")]
        KALABASSA = 79,
        [Display(Name = "KALANCO")]
        KALANCO = 80,
        [Display(Name = "KALAPALO (CALAPALO)")]
        KALAPALO = 81,
        [Display(Name = "KAMAYURA (CAMAIURA, KAMAIURA)")]
        KAMAYURA = 82,
        [Display(Name = "KAMBA (CAMBA)")]
        KAMBA = 83,
        [Display(Name = "KAMBEBA (CAMBEBA, OMAGUA)")]
        KAMBEBA = 84,
        [Display(Name = "KAMBIWA (CAMBIUA)")]
        KAMBIWA = 85,
        [Display(Name = "KAMBIWA PIPIPA (PIPIPA)")]
        KAMBIWAPIPIPA = 86,
        [Display(Name = "KAMPE")]
        KAMPE = 87,
        [Display(Name = "KANAMANTI (KANAMATI, CANAMANTI)")]
        KANAMANTI = 88,
        [Display(Name = "KANAMARI (CANAMARI, KANAMARY, TUKUNA)")]
        KANAMARI = 89,
        [Display(Name = "KANELA APANIEKRA (CANELA)")]
        KANELAAPANIEKRA = 90,
        [Display(Name = "KANELA RANKOKAMEKRA (CANELA)")]
        KANELARANKOKAMEKRA = 91,
        [Display(Name = "KANINDE")]
        KANINDE = 92,
        [Display(Name = "KANOE (CANOE)")]
        KANOE = 93,
        [Display(Name = "KANTARURE (CANTARURE)")]
        KANTARURE = 94,
        [Display(Name = "KAPINAWA (CAPINAUA)")]
        KAPINAWA = 95,
        [Display(Name = "KARAJA (CARAJA)")]
        KARAJA = 96,
        [Display(Name = "KARAJA/JAVAE (JAVAE)")]
        KARAJAJAVAE = 97,
        [Display(Name = "KARAJA/XAMBIOA (KARAJA DO NORTE)")]
        KARAJAXABIOA = 98,
        [Display(Name = "KARAPANA (CARAPANA, MUTEAMASA, UKOPINOPONA)")]
        KARAPANA = 99,
        [Display(Name = "KARAPOTO (CARAPOTO)")]
        KARAPOTO = 100,
        [Display(Name = "KARIPUNA (CARIPUNA)")]
        KARIPUNA = 101,
        [Display(Name = "KARIPUNA DO AMAPA (CARIPUNA)")]
        KARIPUNADOAMAPA = 102,
        [Display(Name = "KARIRI (CARIRI)")]
        KARIRI = 103,
        [Display(Name = "KARIRI-XOCO (CARIRI-CHOCO)")]
        KARIRIXOCO = 104,
        [Display(Name = "KARITIANA (CARITIANA)")]
        KARITIANA = 105,
        [Display(Name = "KATAWIXI (KATAUIXI, KATAWIN, KATAWISI, CATAUICHI)")]
        KATAWIXI = 106,
        [Display(Name = "KATUENA (CATUENA, KATWENA)")]
        KATUENA = 107,
        [Display(Name = "KATUKINA (PEDA DJAPA)")]
        KATUKINA = 108,
        [Display(Name = "KATUKINA DO ACRE")]
        KATUKINADOACRE = 109,
        [Display(Name = "KAXARARI (CAXARARI)")]
        KAXARARI = 110,
        [Display(Name = "KAXINAWA (HUNI-KUIN, CASHINAUA, CAXINAUA)")]
        KAXINAWA = 111,
        [Display(Name = "KAXIXO")]
        KAXIXO = 112,
        [Display(Name = "KAXUYANA (CAXUIANA)")]
        KAXUYANA = 113,
        [Display(Name = "KAYAPO (CAIAPO)")]
        KAYAPO = 114,
        [Display(Name = "KAYAPO KARARAO (KARARAO)")]
        KAYAPOKARARAO = 115,
        [Display(Name = "KAYAPO TXUKAHAMAE (TXUKAHAMAE)")]
        KAYAPOTXUKAHAMAE = 116,
        [Display(Name = "KAYAPO XICRIM (XIKRIN)")]
        KAYAPOXICRIM = 117,
        [Display(Name = "KAYUISANA (CAIXANA, CAUIXANA, KAIXANA)")]
        KAYUISANA = 118,
        [Display(Name = "KINIKINAWA (GUAN, KOINUKOEN, KINIKINAO)")]
        KINIKINAWA = 119,
        [Display(Name = "KIRIRI")]
        KIRIRI = 120,
        [Display(Name = "KOCAMA (COCAMA, KOKAMA)")]
        KOCAMA = 121,
        [Display(Name = "KOKUIREGATEJE")]
        KOKUIREGATEJE = 122,
        [Display(Name = "KORUBO")]
        KORUBO = 123,
        [Display(Name = "KRAHO (CRAO, KRAO)")]
        KRAHO = 124,
        [Display(Name = "KREJE (KRENYE)")]
        KREJE = 125,
        [Display(Name = "KRENAK (BORUN, CRENAQUE)")]
        KRENAK = 126,
        [Display(Name = "KRIKATI (KRINKATI)")]
        KRIKATI = 127,
        [Display(Name = "KUBEO (CUBEO, COBEWA, KUBEWA, PAMIWA, CUBEU)")]
        KUBEO = 128,
        [Display(Name = "KUIKURO (KUIKURU, CUICURO)")]
        KUIKURO = 129,
        [Display(Name = "KUJUBIM (KUYUBI, CUJUBIM)")]
        KUJUBIM = 130,
        [Display(Name = "KULINA PANO (CULINA)")]
        KULINAPANO = 131,
        [Display(Name = "KULINA/MADIHA (CULINA, MADIJA, MADIHA)")]
        KULINAMADILHA = 132,
        [Display(Name = "KURIPAKO (CURIPACO, CURRIPACO, CORIPACO, WAKUENAI)")]
        KURIPAKO = 133,
        [Display(Name = "KURUAIA (CURUAIA)")]
        KURUAIA = 134,
        [Display(Name = "KWAZA (COAIA, KOAIA)")]
        KWAZA = 135,
        [Display(Name = "MACHINERI (MANCHINERI, MANXINERI)")]
        MACHINERI = 136,
        [Display(Name = "MACURAP (MAKURAP)")]
        MACURAP = 137,
        [Display(Name = "MAKU DOW (DOW)")]
        MAKUDOW = 138,
        [Display(Name = "MAKU HUPDA (HUPDA)")]
        MAKUHUPDA = 139,
        [Display(Name = "MAKU NADEB (NADEB)")]
        MAKUNADEB = 140,
        [Display(Name = "MAKU YUHUPDE (YUHUPDE)")]
        MAKUYUHUPDE = 141,
        [Display(Name = "MAKUNA (MACUNA, YEBA-MASA)")]
        MAKUNA = 142,
        [Display(Name = "MAKUXI (MACUXI, MACHUSI, PEMON)")]
        MAKUXI = 143,
        [Display(Name = "MARIMAM (MARIMA)")]
        MARIMAM = 144,
        [Display(Name = "MARUBO")]
        MARUBO = 145,
        [Display(Name = "MATIPU")]
        MATIPU = 146,
        [Display(Name = "MATIS")]
        MATIS = 147,
        [Display(Name = "MATSE (MAYORUNA)")]
        MATSE = 148,
        [Display(Name = "MAXAKALI (MAXACALI)")]
        MAXAKALI = 149,
        [Display(Name = "MAYA (MAYA)")]
        MAYA = 150,
        [Display(Name = "MAYTAPU")]
        MAYTAPU = 151,
        [Display(Name = "MEHINAKO (MEINAKU, MEINACU)")]
        MEHINAKO = 152,
        [Display(Name = "MEKEN (MEQUEM, MEKHEM, MICHENS)")]
        MEKEN = 153,
        [Display(Name = "MENKY (MYKY, MUNKU, MENKI, MYNKY)")]
        MENKY = 154,
        [Display(Name = "MIRANHA (MIRANHA, MIRANA)")]
        MIRANHA = 155,
        [Display(Name = "MIRITI TAPUIA (MIRITI-TAPUYA, BUIA-TAPUYA)")]
        MIRITITAPUIA = 156,
        [Display(Name = "MUNDURUKU (MUNDURUCU)")]
        MUNDURUKU = 157,
        [Display(Name = "MURA")]
        MURA = 158,
        [Display(Name = "NAHUKWA (NAFUQUA)")]
        NAHUKWA = 159,
        [Display(Name = "NAMBIKWARA DO CAMPO (HALOTESU, KITHAULU, WAKALITESU, SAWENTES, MANDUKA)")]
        NAMBIKWARADOCAMPO = 160,
        [Display(Name = "NAMBIKWARA DO NORTE (NEGAROTE, MAMAINDE, LATUNDE, SABANE E MANDUKA, TAWANDE)")]
        NAMBIKWARADONORTE = 161,
        [Display(Name = "NAMBIKWARA DO SUL (WASUSU, HAHAINTESU, ALANTESU, WAIKISU, ALAKETESU, WASUSU, SARARE)")]
        NAMBIKWARADOSUL = 162,
        [Display(Name = "NARAVUTE (NARUVOTO)")]
        NARAVUTE = 163,
        [Display(Name = "NAWA (NAUA)")]
        NAWA = 164,
        [Display(Name = "NUKINI (NUQUINI, NUKUINI)")]
        NUKINI = 165,
        [Display(Name = "OFAIE (OFAYE-XAVANTE)")]
        OFAIE = 166,
        [Display(Name = "ORO WIN")]
        OROWIN = 167,
        [Display(Name = "PAIAKU (JENIPAPO-KANINDE)")]
        PAIAKU = 168,
        [Display(Name = "PAKAA NOVA (WARI, PACAAS NOVOS)")]
        PAKAANOVA = 169,
        [Display(Name = "PALIKUR (AUKWAYENE, AUKUYENE, PALIKU''ENE)")]
        PALIKUR = 170,
        [Display(Name = "PANARA (KRENHAKARORE, KRENAKORE, KRENA-KARORE)")]
        PANARA = 171,
        [Display(Name = "PANKARARE (PANCARARE)")]
        PANKARARE = 172,
        [Display(Name = "PANKARARU (PANCARARU)")]
        PANKARARU = 173,
        [Display(Name = "PANKARARU KALANKO (KALANKO)")]
        PANKARARUKALANKO = 174,
        [Display(Name = "PANKARARU KARUAZU (KARUAZU)")]
        PANKARARUKARUAZU = 175,
        [Display(Name = "PANKARU (PANCARU)")]
        PANKARU = 176,
        [Display(Name = "PARAKANA (PARACANA, APITEREWA, AWAETE)")]
        PARAKANA = 177,
        [Display(Name = "PARECI (PARESI, HALITI)")]
        PARECI = 178,
        [Display(Name = "PARINTINTIN")]
        PARINTINTIN = 179,
        [Display(Name = "PATAMONA (KAPON)")]
        PATAMONA = 180,
        [Display(Name = "PATAXO")]
        PATAXO = 181,
        [Display(Name = "PATAXO HA-HA-HAE")]
        PATAXOHAHAHAE = 182,
        [Display(Name = "PAUMARI (PALMARI)")]
        PAUMARI = 183,
        [Display(Name = "PAUMELENHO")]
        PAUMELENHO = 184,
        [Display(Name = "PIRAHA (MURA PIRAHA)")]
        PIRAHA = 185,
        [Display(Name = "PIRATUAPUIA (PIRATAPUYA, PIRATAPUYO, PIRA-TAPUYA, WAIKANA)")]
        PIRATUAPUIA = 186,
        [Display(Name = "PITAGUARI")]
        PITAGUARI = 187,
        [Display(Name = "POTIGUARA")]
        POTIGUARA = 188,
        [Display(Name = "POYANAWA (POIANAUA)")]
        POYANAWA = 189,
        [Display(Name = "RIKBAKTSA (CANOEIROS, ERIGPAKTSA)")]
        RIKBAKTSA = 190,
        [Display(Name = "SAKURABIAT(MEKENS, SAKIRABIAP, SAKIRABIAR)")]
        SAKURABIAT = 191,
        [Display(Name = "SATERE-MAWE (SATERE-MAUE)")]
        SATEREMAWE = 192,
        [Display(Name = "SHANENAWA (KATUKINA)")]
        SHANENAWA = 193,
        [Display(Name = "SIRIANO (SIRIA-MASA)")]
        SIRIANO = 194,
        [Display(Name = "SURIANA")]
        SURIANA = 195,
        [Display(Name = "SURUI DE RONDONIA (PAITER)")]
        SURUIDERONDONIA = 196,
        [Display(Name = "SURUI DO PARA (AIKEWARA)")]
        SURUIDOPARA = 197,
        [Display(Name = "SUYA (SUIA/KISEDJE)")]
        SUYA = 198,
        [Display(Name = "TAPAYUNA (BEICO-DE-PAU)")]
        TAPAYUNA = 199,
        [Display(Name = "TAPEBA")]
        TAPEBA = 200,
        [Display(Name = "TAPIRAPE (TAPI''IRAPE)")]
        TAPIRAPE = 201,
        [Display(Name = "TAPUIA (TAPUIA-XAVANTE, TAPUIO)")]
        TAPUIA = 202,
        [Display(Name = "TARIANO (TARIANA, TALIASERI)")]
        TARIANO = 203,
        [Display(Name = "TAUREPANG (TAULIPANG, PEMON, AREKUNA, PAGEYN)")]
        TAUREPANG = 204,
        [Display(Name = "TEMBE")]
        TEMBE = 205,
        [Display(Name = "TENHARIM")]
        TENHARIM = 206,
        [Display(Name = "TERENA")]
        TERENA = 207,
        [Display(Name = "TICUNA (TIKUNA, TUKUNA, MAGUTA)")]
        TICUNA = 208,
        [Display(Name = "TINGUI BOTO")]
        TINGUIBOTO = 209,
        [Display(Name = "TIRIYO EWARHUYANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)")]
        TIRIYOEWARHUYANA = 210,
        [Display(Name = "TIRIYO KAH''YANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)")]
        TIRIYOKAH = 211,
        [Display(Name = "TIRIYO TSIKUYANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)")]
        TIRIYOTSIKUYANA = 212,
        [Display(Name = "TORA")]
        TORA = 213,
        [Display(Name = "TREMEMBE")]
        TREMEMBE = 214,
        [Display(Name = "TRUKA")]
        TRUKA = 215,
        [Display(Name = "TRUMAI")]
        TRUMAI = 216,
        [Display(Name = "TSOHOM DJAPA (TSUNHUM-DJAPA)")]
        TSOHOMDJAPA = 217,
        [Display(Name = "TUKANO (TUCANO, YE''PA-MASA, DASEA)")]
        TUKANO = 218,
        [Display(Name = "TUMBALALA")]
        TUMBALALA = 219,
        [Display(Name = "TUNAYANA")]
        TUNAYANA = 220,
        [Display(Name = "TUPARI")]
        TUPARI = 221,
        [Display(Name = "TUPINAMBA")]
        TUPINAMBA = 222,
        [Display(Name = "TUPINIQUIM")]
        TUPINIQUIM = 223,
        [Display(Name = "TURIWARA")]
        TURIWARA = 224,
        [Display(Name = "TUXA")]
        TUXA = 225,
        [Display(Name = "TUYUKA (TUIUCA, DOKAPUARA, UTAPINOMAKAPHONA)")]
        TUYUKA = 226,
        [Display(Name = "TXIKAO (TXICAO, IKPENG)")]
        TXIKAO = 227,
        [Display(Name = "UMUTINA (OMOTINA, BARBADOS)")]
        UMUTINA = 228,
        [Display(Name = "URU-EU-WAU-WAU (URUEU-UAU-UAU, URUPAIN, URUPA)")]
        URUEUWASWAU = 229,
        [Display(Name = "WAI WAI HIXKARYANA (HIXKARYANA)")]
        WAIWAI = 230,
        [Display(Name = "WAI WAI KARAFAWYANA (KARAFAWYANA, KARA-PAWYANA)")]
        WAIWAIKARAFAWYANA = 231,
        [Display(Name = "WAI WAI XEREU (XEREU)")]
        WAIWAIXEREU = 232,
        [Display(Name = "WAI WAI KATUENA (KATUENA)")]
        WAIWAIKATUENA = 233,
        [Display(Name = "WAI WAI MAWAYANA (MAWAYANA)")]
        WAIWAIMAWAYANA = 234,
        [Display(Name = "WAIAPI (WAYAMPI, OYAMPI, WAYAPY, )")]
        WAIAPI = 235,
        [Display(Name = "WAIMIRI ATROARI (KINA)")]
        WAIMIRIATROARI = 236,
        [Display(Name = "WANANO (UANANO, WANANA)")]
        WANANO = 237,
        [Display(Name = "WAPIXANA (UAPIXANA, VAPIDIANA, WAPISIANA, WAPISHANA)")]
        WAPIXANA = 238,
        [Display(Name = "WAREKENA (UAREQUENA, WEREKENA)")]
        WAREKENA = 239,
        [Display(Name = "WASSU")]
        WASSU = 240,
        [Display(Name = "WAURA (UAURA, WAUJA)")]
        WAURA = 241,
        [Display(Name = "WAYANA (WAIANA, UAIANA)")]
        WAYANA = 242,
        [Display(Name = "WITOTO (UITOTO, HUITOTO)")]
        WITOTO = 243,
        [Display(Name = "XAKRIABA (XACRIABA)")]
        XAKRIABA = 244,
        [Display(Name = "XAVANTE (A''UWE, AKWE, AWEN, AKWEN)")]
        XAVANTE = 245,
        [Display(Name = "XERENTE (AKWE, AWEN, AKWEN)")]
        XERENTE = 246,
        [Display(Name = "XETA")]
        XETA = 247,
        [Display(Name = "XIPAIA (SHIPAYA, XIPAYA)")]
        XIPAIA = 248,
        [Display(Name = "XOKLENG (SHOKLENG, XOCLENG)")]
        XOKLENG = 249,
        [Display(Name = "XOKO (XOCO, CHOCO)")]
        XOKO = 250,
        [Display(Name = "XUKURU (XUCURU)")]
        XUKURU = 251,
        [Display(Name = "XUKURU KARIRI (XUCURU-KARIRI)")]
        XUKURUKARIRI = 252,
        [Display(Name = "YAIPIYANA")]
        YAIPIYANA = 253,
        [Display(Name = "YAMINAWA (JAMINAWA, IAMINAWA)")]
        YAMINAWA = 254,
        [Display(Name = "YANOMAMI NINAM (IANOMAMI, IANOAMA, XIRIANA)")]
        YANOMAMININAM = 255,
        [Display(Name = "YANOMAMI SANUMA (IANOMAMI, IANOAMA, XIRIANA)")]
        YANOMAMISANUMA = 256,
        [Display(Name = "YANOMAMI YANOMAM (IANOMAMI, IANOAMA, XIRIANA)")]
        YANOMAMIYANOMAM = 257,
        [Display(Name = "YAWALAPITI (IAUALAPITI)")]
        YAWALAPITI = 258,
        [Display(Name = "YAWANAWA (IAUANAUA)")]
        YAWANAWA = 259,
        [Display(Name = "YEKUANA (MAIONGON, YE''KUANA, YEKWANA, MAYONGONG)")]
        YEKUANA = 260,
        [Display(Name = "YUDJA (JURUNA, YURUNA)")]
        YUDJA = 261,
        [Display(Name = "ZO''E (POTURU)")]
        ZOE = 262,
        [Display(Name = "ZORO (PAGEYN)")]
        ZORO = 263,
        [Display(Name = "ZURUAHA (SOROWAHA, SURUWAHA)")]
        ZURUAHA = 264,
    }
}
